### ISSUE TITLE
代码里有高可用功能么？

### ISSUE THREAD

**Issue by shpswd** [ADBSQL/AntDB#90]
您好，高可用Guard在代码中的那个位置！

**Comment by yuechangying** [comment]
有高可用功能
在 doctor模块

**Comment by yuechangying** [comment]
有的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ADBSQL/AntDB"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月18日(星期六) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ADBSQL/AntDB] 代码里有高可用功能么？ (#90)





 
Closed #90.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
